version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: site-courselandia-ru-app
    container_name: site-courselandia-ru-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - ${APP_PORT}:3000
    networks:
      - network
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: site-courselandia-ru-redis
    restart: unless-stopped
    ports:
      - ${DOCKER_REDIS_PORT}:${REDIS_PORT}
    networks:
      - network

networks:
  network:
    driver: bridge
