version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: site-courselandia-ru-app
    container_name: site-courselandia-ru-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - ${APP_PORT}:3000
    networks:
      - network

networks:
  network:
    driver: bridge
